services:
  carla:
    image: carlasim/carla:$CARLA_VERSION
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1 # Fix a bug with QT
      - SDL_VIDEODRIVER=x11
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./asound.conf:/etc/asound.conf
      - carla-data:/home/carla
    command: ["bash", "./CarlaUE4.sh", "-vulkan", "-quality-level=Low", "-fps=5", "-carla-port=2000"]

  tf:
    build:
      context: docker/tf
      dockerfile: Dockerfile
    image: hbarros1/caraware-tf:$CARAWARE_VERSION
    # runtime: nvidia
    privileged: true
    network_mode: "host"
    environment:
      - CARLA_ROOT=/home/carla
      - PYTHONPATH=/home/carla/PythonAPI/carla/dist/carla-$CARLA_VERSION-py3.7-linux-x86_64.egg
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1 # Fix a bug with QT
      - SDL_VIDEODRIVER=x11
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
    working_dir: /app
    user: 1000:1000
    volumes:
      - .:/app
      - carla-data:/home/carla
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./asound.conf:/etc/asound.conf
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ${HOME}:${HOME}
    command: tail -F /dev/null

  ros:
    build:
      context: docker/ros
      dockerfile: Dockerfile
    image: hbarros1/caraware-ros:$CARAWARE_VERSION
    network_mode: "host"
    working_dir: /root/carla_ws
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1 # Fix a bug with QT
      - SDL_VIDEODRIVER=
      - CARLA_ROOT=/home/carla
      - PYTHONPATH=/home/carla/PythonAPI/carla/dist/carla-$CARLA_VERSION-py3.7-linux-x86_64.egg:/home/carla/PythonAPI/carla
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./asound.conf:/etc/asound.conf
      - ${HOME}/carla_ws:/root/carla_ws
      - carla-data:/home/carla
    command: ["bash", "-c", "source /opt/ros/$ROS_DISTRO/setup.bash && source /root/carla_ws/install/setup.bash && ros2 launch carla_ros_bridge carla_ros_bridge.launch.py carla_host:=localhost carla_port:=2000 timeout:=10 passive:=True register_all_sensors:=True"]

volumes:
  carla-data:
    external: true