services:
  carla:
    image: carlasim/carla:0.9.15
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    # ports:
    #  - "2000-2002:2000-2002"
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1 # Fix a bug with QT
      - SDL_VIDEODRIVER=x11
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./asound.conf:/etc/asound.conf
      # - carla-data:/home/carla
    command: ["bash", "./CarlaUE4.sh", "-vulkan", "-quality-level=Low", "-fps=10", "-carla-port=2000"]

  caraware:
    build:
      context: .
      dockerfile: Dockerfile
    image: caraware:latest
    runtime: nvidia
    network_mode: "host"
    environment:
      - CARLA_ROOT=/home/carla
      - PYTHONPATH=/home/carla/PythonAPI/carla/dist/carla-0.9.15-py3.7-linux-x86_64.egg
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1 # Fix a bug with QT
      - SDL_VIDEODRIVER=x11
    working_dir: /app
    user: 1000:1000
    volumes:
      - .:/app
      - carla-data:/home/carla
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ${HOME}:${HOME}
    depends_on:
      - carla
    command: tail -F anything

volumes:
  carla-data:
    external: true