services:
  tf:
    depends_on:
      - carla
      - ros
    command: [
      "/app/entrypoint_tf.sh",
      "--wait-for-carla",
      "--run-main", "train"
    ]

  ros:
    depends_on:
      - carla
    command: [
      "/root/carla_ws/src/CarAware/entrypoint_ros.sh",
      "ekf_to_zmq:=true"
    ]
