services:
  tf:
    depends_on:
      - carla
    command: [
      "/app/entrypoint_tf.sh",
      "--wait-for-carla",
      "--run-main", "train"
    ]

  ros:
    depends_on:
      - carla
      - tf
    command: [
      "/root/carla_ws/src/CarAware/entrypoint_ros_carla.sh"
    ]
